"""sync schema

Revision ID: 117d57bde816
Revises: 
Create Date: 2026-05-12 13:29:37.337072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '117d57bde816'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('block_timesheets')
    op.drop_table('time_sheet_comments')
    op.drop_table('timesheet')
    op.drop_index(op.f('ix_holidays_id'), table_name='holidays')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_salaries_id'), table_name='salaries')
    op.drop_table('salaries')
    op.add_column('cms_images', sa.Column('status', sa.Boolean(), nullable=False))
    op.alter_column('emp_account_details', 'acc_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('process', 'creation_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('process', 'last_modified_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('profile', 'last_modified_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('sub_process', 'creation_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('sub_process', 'last_modified_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.BigInteger(),
               nullable=True)
    op.create_foreign_key(None, 'users', 'role', ['role'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'role',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('sub_process', 'last_modified_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('sub_process', 'creation_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('profile', 'last_modified_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('process', 'last_modified_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('process', 'creation_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('emp_account_details', 'acc_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('cms_images', 'status')
    op.create_table('salaries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('basic', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('hra', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bonus', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('deductions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('month', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('salaries_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('salaries_pkey'))
    )
    op.create_index(op.f('ix_salaries_id'), 'salaries', ['id'], unique=False)
    op.create_table('holidays',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('holiday_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('holiday_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('holidays_pkey'))
    )
    op.create_index(op.f('ix_holidays_id'), 'holidays', ['id'], unique=False)
    op.create_table('timesheet',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('manager_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('hours', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('select_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'reject', 'refer_back', name='timesheet_status'), autoincrement=False, nullable=False),
    sa.Column('manager_comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name=op.f('timesheet_manager_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('timesheet_project_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('timesheet_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('timesheet_pkey'))
    )
    op.create_table('time_sheet_comments',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('timesheet_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('comment_history', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'reject', 'refer_back', name='timesheet_comment_status'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['timesheet_id'], ['timesheet.id'], name=op.f('time_sheet_comments_timesheet_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('time_sheet_comments_pkey'))
    )
    op.create_table('block_timesheets',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('timesheet_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('is_block', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('block_timesheets_approved_by_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('block_timesheets_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('block_timesheets_pkey')),
    sa.UniqueConstraint('timesheet_date', 'user_id', name=op.f('unique_block_per_day_user'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
